### PR TITLE
Unbreak build on x86

### LINKED ISSUE #34: Fails to build on x86
Found on FreeBSD [i386](http://beefy10.nyi.freebsd.org/data/112i386-default/490102/logs/errors/citra-qt5-s20190111.log):

```c++
In file included from src/test_generator.cpp:10:
src/./test.h:37:1: fatal error: static_assert failed
static_assert(sizeof(TestCase) == 4312);
^             ~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

### PR DESCRIPTION
**Pull request by jbeich**
Fixes #34

### CODE REVIEW

**Comment by wwylele** [comment]
Do you know where the layout difference come from? If it is a missing/extra padding in between some members, adding padding field at the end is incorrect; if it is just size difference due to not respecting `u64` 8-byte alignment, `alignas(8)` might be a better way to go.

**Comment by wwylele** [comment]
Closing due to inactivity

**Comment by jbeich** [comment]
I confirm, adding `alignas(8)`  helps. Can you reopen or cherry-pick 5862fd000353?

**Comment by wwylele** [comment]
Github doesn't allow me to reopen this. Please open a new PR and let CI check stuff because I currently don't have the dev environment set up.

**Comment by wwylele** [comment]
Also adding `alignas(8)` on the top level struct isn't always correct either. It ensures the correct total size, but doesn't ensure the inner layout (for example all fields after a u64 field might be offset by 4 bytes). It should be added to all `u64`-type fields

**Pull request closed without merging**
